import './globals.css'; // Asegúrate de importar tus estilos globales
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'SOL EDUCATIVO | RURANJO',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  

  return (
    <html lang="en" className='!scroll-smooth'>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className} suppressHydrationWarning={true} >
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}